version: '3'

services:
  flask-app:
    image: elemen0p/trigo_ex:latest
    container_name: inventory-service
    ports:
      - "1337:1337"

  adapter:
    image: python:3-alpine
    container_name: adapter
    volumes:
      - ./adapter.py:/app/adapter.py
      - prometheus_data:/etc/prometheus/targets
    command: ["python", "/app/adapter.py"]
    depends_on:
      - flask-app

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/etc/prometheus/targets
    ports:
      - "9090:9090"
    depends_on:
      - adapter

volumes:
  prometheus_data:
